### ISSUE TITLE
Provider rebuild fails on OpenStack (SMOG)

### ISSUE THREAD

**Issue by ahellander** [Molns/molns#19]
I have started getting this error when doing a setup/rebuild

[43/44] EXECUTING...    sync
Installation complete in 1451.48908401s
Traceback (most recent call last):
  File "./molns.py", line 1005, in <module>
    parseArgs()
  File "./molns.py", line 995, in parseArgs
    cmd.run(arg_list[1:], config_dir=config_dir)
  File "./molns.py", line 97, in run
    return c.run(args[1:], config_dir=config_dir)
  File "./molns.py", line 127, in run
    self.function(args, config=config)
  File "./molns.py", line 801, in provider_rebuild
    provider_obj['molns_image_name'] = provider_obj.create_molns_image()
  File "/Users/andreash/github/MOLNs/molns/MolnsLib/OpenStackProvider.py", line 181, in create_molns_image
    self._delete_floating_ip(ip)
  File "/Users/andreash/github/MOLNs/molns/MolnsLib/OpenStackProvider.py", line 347, in _delete_floating_ip
    raise ProviderException("Could not delete floating ip '{0}'".format(ip))
MolnsLib.molns_provider.ProviderException: Could not delete floating ip '130.238.29.40'

**Comment by briandrawert** [comment]
I believe I fixed that with this commit: https://github.com/briandrawert/molns/commit/818cf71a3ab6cb9e8639fbfb9fab6181fda58393

**Comment by ahellander** [comment]
## Send a PR to the main repo?

Andreas Hellander
Associate Professor, Scientific Computing
Division of Scientific Computing
Department of Information Technology
Uppsala University

On Apr 20, 2015, at 6:02 PM, Brian Drawert <notifications@github.com<mailto:notifications@github.com>> wrote:

I believe I fixed that with this commit: briandrawert@818cf71https://github.com/briandrawert/molns/commit/818cf71a3ab6cb9e8639fbfb9fab6181fda58393
