### ISSUE TITLE
Fails to make base image (Ubuntu 14.04)

### ISSUE THREAD

**Issue by ahellander** [Molns/molns#29]
[20/44] EXECUTING...    sudo pip install python-novaclient
[21/44] EXECUTING...    sudo pip install python-keystoneclient
RETRY 1.....    sudo pip install python-keystoneclient
RETRY 2.....    sudo pip install python-keystoneclient
RETRY 3.....    sudo pip install python-keystoneclient
RETRY 4.....    sudo pip install python-keystoneclient
Traceback (most recent call last):
 File "/home/fredrik/molns/molns-master/molns.py", line 1005, in <module>
   parseArgs()
 File "/home/fredrik/molns/molns-master/molns.py", line 995, in parseArgs
   cmd.run(arg_list[1:], config_dir=config_dir)
 File "/home/fredrik/molns/molns-master/molns.py", line 97, in run
   return c.run(args[1:], config_dir=config_dir)
 File "/home/fredrik/molns/molns-master/molns.py", line 127, in run
   self.function(args, config=config)
 File "/home/fredrik/molns/molns-master/molns.py", line 777, in
provider_setup
   provider_obj['molns_image_name'] = provider_obj.create_molns_image()
 File "/home/fredrik/molns/molns-master/MolnsLib/OpenStackProvider.py",
line 181, in create_molns_image
   self._delete_floating_ip(ip)
 File "/home/fredrik/molns/molns-master/MolnsLib/OpenStackProvider.py",
line 347, in _delete_floating_ip
   raise ProviderException("Could not delete floating ip '{0}'".format(ip))
MolnsLib.molns_provider.ProviderException: Could not delete floating ip
'130.238.29.38'

**Comment by ahellander** [comment]
Solution is to upgrade pip itself. 

Time to move to 14.10??

**Comment by briandrawert** [comment]
Fixed in https://github.com/Molns/molns/pull/30
